version: '2'
services:
  ptes-apm:
    scale: 4
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 8200
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      reinitializing_timeout: 60000
