version: '2'
services:
  slack:
    retain_ip: true
    scale: 2
    start_on_create: true
  LB-slack-dev:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - priority: 1
        protocol: tcp
        service: slack
        source_port: 5000
        target_port: 5000
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      reinitializing_timeout: 60000
