version: '2'
services:
  11-dd-adwords-dogfood:
    scale: 2
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 5000
      recreate_on_quorum_strategy_config:
        quorum: 1
      port: 8080
      unhealthy_threshold: 3
      initializing_timeout: 180000
      interval: 5000
      strategy: recreateOnQuorum
      reinitializing_timeout: 180000
  09-dd-web-socket-dogfood:
    scale: 2
    start_on_create: true
  Rabbitmq-dogfood:
    scale: 1
    start_on_create: true
  02-dd-admin-dogfood:
    drain_timeout_ms: 3000
    scale: 2
    start_on_create: true
  dd-redis-cluster-dogfood:
    drain_timeout_ms: 1000
    scale: 1
    start_on_create: true
  dd-zookeeper-dogfood:
    retain_ip: true
    scale: 3
    start_on_create: true
  zk-volume:
    retain_ip: true
    scale: 3
    start_on_create: true
  07-dd-gather-dogfood:
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 5000
      recreate_on_quorum_strategy_config:
        quorum: 1
      port: 8080
      unhealthy_threshold: 3
      initializing_timeout: 180000
      interval: 5000
      strategy: recreateOnQuorum
      reinitializing_timeout: 180000
  04-dd-redis-dogfood:
    scale: 2
    start_on_create: true
  08-dd-permision-dogfood:
    scale: 2
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 5000
      recreate_on_quorum_strategy_config:
        quorum: 1
      port: 8080
      unhealthy_threshold: 3
      initializing_timeout: 180000
      interval: 5000
      strategy: recreateOnQuorum
      reinitializing_timeout: 180000
  05-dd-middle-dogfood:
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 11000
      recreate_on_quorum_strategy_config:
        quorum: 1
      port: 8080
      unhealthy_threshold: 3
      initializing_timeout: 180000
      interval: 5000
      strategy: recreateOnQuorum
      reinitializing_timeout: 180000
  12-dd-log-dogfood:
    scale: 2
    start_on_create: true
  03-dd-dash-dogfood:
    scale: 2
    start_on_create: true
  06-dd-rest-dogfood:
    scale: 1
    start_on_create: true
  zk-conf:
    retain_ip: true
    scale: 3
    start_on_create: true
  13-dd-mobile-dogfood:
    scale: 2
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 10000
      recreate_on_quorum_strategy_config:
        quorum: 1
      port: 80
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 10000
      strategy: recreateOnQuorum
      request_line: GET "/" "HTTP/1.0"
      reinitializing_timeout: 60000
  10-dd-provider-dogfood:
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 5000
      recreate_on_quorum_strategy_config:
        quorum: 1
      port: 8080
      unhealthy_threshold: 3
      initializing_timeout: 180000
      interval: 5000
      strategy: recreateOnQuorum
      reinitializing_timeout: 180000
