version: '2'
services:
  cadvisor:
    mem_limit: 134217728
    image: google/cadvisor:latest
    stdin_open: true
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    tty: true
    ports:
    - 18080:8080/tcp
    labels:
      io.rancher.scheduler.global: 'true'
  prometheus-rancher-exporter:
    mem_limit: 134217728
    image: infinityworks/prometheus-rancher-exporter:v0.22.52
    tty: true
    ports:
    - 9173:9173/tcp
    labels:
      io.rancher.container.agent.role: environment
      io.rancher.container.create_agent: 'true'
