version: '2'
services:
  cadvisor:
    start_on_create: true
  prometheus-rancher-exporter:
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 5000
      port: 9173
      unhealthy_threshold: 3
      interval: 5000
      strategy: recreate
