---
#- name: pull calico image
#  shell: 'docker pull {{ item }}'
#  with_items:
#    - quay.io/calico/node:v3.2.0
#    - quay.io/calico/cni:v3.2.0
#    - quay.io/calico/kube-controllers:v3.2.0

- name: copy kubernetes.tar.gz
  copy: 'src={{ tar_local }}/kube{{ k8s_version }}.tar.gz dest=/root/ mode=0644'

- name: init every node 
  shell: 'cd /root && {{ item }}'
  with_items:
  - kubeadm reset -f || true && rm -rf /var/lib/etcd && rm -rf /var/etcd
  - tar zxvf kube{{ k8s_version }}.tar.gz
  - cd kube/shell && sh init.sh

- name: ntp config
  shell: '{{ item }}'
  with_items:
  - yum install ntpdate -y
  - ntpdate 0.asia.pool.ntp.org  
  when:  ( need_ntp == 'true' )