version: '2'
services:
  LB-jp-dc-staging:
    image: rancher/lb-service-haproxy:v0.9.1
    ports:
    - 8200:8200/tcp
    labels:
      io.rancher.scheduler.affinity:host_label: traefik_lb=true
      io.rancher.container.agent.role: environmentAdmin,agent
      io.rancher.container.agent_service.drain_provider: 'true'
      io.rancher.container.create_agent: 'true'
